spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: booking
    password: booking

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}]"